--------------------------------------------------------
--  File created - Monday-July-06-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENT_MASTER
--------------------------------------------------------

  CREATE TABLE "STAFF"."CLIENT_MASTER" 
   (	"CLIENT_NO" VARCHAR2(6 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"ADDRESS1" VARCHAR2(30 BYTE), 
	"ADDRESS2" VARCHAR2(30 BYTE), 
	"CITY" VARCHAR2(15 BYTE), 
	"STATE" VARCHAR2(15 BYTE), 
	"PINCODE" NUMBER(6,0), 
	"BAL_DUE" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into STAFF.CLIENT_MASTER
SET DEFINE OFF;
Insert into STAFF.CLIENT_MASTER (CLIENT_NO,NAME,ADDRESS1,ADDRESS2,CITY,STATE,PINCODE,BAL_DUE) values ('0001','Ivan',null,null,'Bombay','Maharashtra',400054,15000);
Insert into STAFF.CLIENT_MASTER (CLIENT_NO,NAME,ADDRESS1,ADDRESS2,CITY,STATE,PINCODE,BAL_DUE) values ('0002','Vandana',null,null,'Madras','Tamilnadu',780001,0);
Insert into STAFF.CLIENT_MASTER (CLIENT_NO,NAME,ADDRESS1,ADDRESS2,CITY,STATE,PINCODE,BAL_DUE) values ('0003','Pramada',null,null,'Bombay','Maharashtra',400057,5000);
Insert into STAFF.CLIENT_MASTER (CLIENT_NO,NAME,ADDRESS1,ADDRESS2,CITY,STATE,PINCODE,BAL_DUE) values ('0004','Basu',null,null,'Bombay','Maharashtra',400056,0);
Insert into STAFF.CLIENT_MASTER (CLIENT_NO,NAME,ADDRESS1,ADDRESS2,CITY,STATE,PINCODE,BAL_DUE) values ('0005','Ravi',null,null,'Delhi','Gujarat',100001,2000);
Insert into STAFF.CLIENT_MASTER (CLIENT_NO,NAME,ADDRESS1,ADDRESS2,CITY,STATE,PINCODE,BAL_DUE) values ('0006','Rukmini',null,null,'Bombay','Maharashtra',400050,0);
