--------------------------------------------------------
--  File created - Monday-July-06-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRODUCT_MASTER
--------------------------------------------------------

  CREATE TABLE "STAFF"."PRODUCT_MASTER" 
   (	"PRODUCT_NO" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(20 BYTE), 
	"PROFIT_PERCENT" NUMBER, 
	"UNIT_MEASURE" VARCHAR2(20 BYTE), 
	"QTY_ON_HAND" NUMBER, 
	"REORDER_LVL" NUMBER, 
	"SELL_PRICE" NUMBER, 
	"COST_PRICE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into STAFF.PRODUCT_MASTER
SET DEFINE OFF;
Insert into STAFF.PRODUCT_MASTER (PRODUCT_NO,DESCRIPTION,PROFIT_PERCENT,UNIT_MEASURE,QTY_ON_HAND,REORDER_LVL,SELL_PRICE,COST_PRICE) values ('P00001','1.44floppies',5,'piece',100,20,525,500);
Insert into STAFF.PRODUCT_MASTER (PRODUCT_NO,DESCRIPTION,PROFIT_PERCENT,UNIT_MEASURE,QTY_ON_HAND,REORDER_LVL,SELL_PRICE,COST_PRICE) values ('P03453','Monitors',6,'piece',10,3,12000,11200);
Insert into STAFF.PRODUCT_MASTER (PRODUCT_NO,DESCRIPTION,PROFIT_PERCENT,UNIT_MEASURE,QTY_ON_HAND,REORDER_LVL,SELL_PRICE,COST_PRICE) values ('P06734','Mouse',5,'piece',20,5,1050,500);
Insert into STAFF.PRODUCT_MASTER (PRODUCT_NO,DESCRIPTION,PROFIT_PERCENT,UNIT_MEASURE,QTY_ON_HAND,REORDER_LVL,SELL_PRICE,COST_PRICE) values ('P07865','1.22floppies',5,'piece',100,20,525,500);
Insert into STAFF.PRODUCT_MASTER (PRODUCT_NO,DESCRIPTION,PROFIT_PERCENT,UNIT_MEASURE,QTY_ON_HAND,REORDER_LVL,SELL_PRICE,COST_PRICE) values ('P07868','Keyboards',2,'piece',10,3,3150,3050);
Insert into STAFF.PRODUCT_MASTER (PRODUCT_NO,DESCRIPTION,PROFIT_PERCENT,UNIT_MEASURE,QTY_ON_HAND,REORDER_LVL,SELL_PRICE,COST_PRICE) values ('P07885','CD Drive',2.5,'piece',10,3,5250,5100);
Insert into STAFF.PRODUCT_MASTER (PRODUCT_NO,DESCRIPTION,PROFIT_PERCENT,UNIT_MEASURE,QTY_ON_HAND,REORDER_LVL,SELL_PRICE,COST_PRICE) values ('P07965','540 HDD',4,'piece',10,3,8400,8000);
Insert into STAFF.PRODUCT_MASTER (PRODUCT_NO,DESCRIPTION,PROFIT_PERCENT,UNIT_MEASURE,QTY_ON_HAND,REORDER_LVL,SELL_PRICE,COST_PRICE) values ('P07975','1.44 Drive',5,'piece',10,3,1050,1000);
Insert into STAFF.PRODUCT_MASTER (PRODUCT_NO,DESCRIPTION,PROFIT_PERCENT,UNIT_MEASURE,QTY_ON_HAND,REORDER_LVL,SELL_PRICE,COST_PRICE) values ('P08865','1.22 Drive',5,'piece',2,3,1050,1000);
