--------------------------------------------------------
--  File created - Wednesday-July-22-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ASTUDENT
--------------------------------------------------------

  CREATE TABLE "JPANDYA"."ASTUDENT" 
   (	"STUDENT_ID" NUMBER(6,0), 
	"STUDENT_NAME" VARCHAR2(20 BYTE), 
	"DEPT_ID" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JPANDYA.ASTUDENT
SET DEFINE OFF;
Insert into JPANDYA.ASTUDENT (STUDENT_ID,STUDENT_NAME,DEPT_ID) values (3,'James',null);
Insert into JPANDYA.ASTUDENT (STUDENT_ID,STUDENT_NAME,DEPT_ID) values (1,'Harry',1);
Insert into JPANDYA.ASTUDENT (STUDENT_ID,STUDENT_NAME,DEPT_ID) values (2,'Sarah',2);
Insert into JPANDYA.ASTUDENT (STUDENT_ID,STUDENT_NAME,DEPT_ID) values (4,'Dave',2);
Insert into JPANDYA.ASTUDENT (STUDENT_ID,STUDENT_NAME,DEPT_ID) values (5,'Michael',null);
Insert into JPANDYA.ASTUDENT (STUDENT_ID,STUDENT_NAME,DEPT_ID) values (6,'Holy',1);
--------------------------------------------------------
--  DDL for Index SYS_C007716
--------------------------------------------------------

  CREATE UNIQUE INDEX "JPANDYA"."SYS_C007716" ON "JPANDYA"."ASTUDENT" ("STUDENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ASTUDENT
--------------------------------------------------------

  ALTER TABLE "JPANDYA"."ASTUDENT" ADD PRIMARY KEY ("STUDENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
