insert into Town_Youngsters values (1,1,1,1,1);
insert into Town_Youngsters values (1,0,1,1,1);
insert into Town_Youngsters values (1,0,0,0,0);
insert into Town_Youngsters values (0,1,1,1,0);
insert into Town_Youngsters values (1,0,1,1,1);
insert into Town_Youngsters values (0,0,1,1,0);
insert into Town_Youngsters values (0,0,0,0,1);
insert into Town_Youngsters values (0,0,1,1,0);
insert into Town_Youngsters values (0,1,1,1,1);
insert into Town_Youngsters values (1,0,1,1,0);
insert into Town_Youngsters values (0,0,1,0,0);
insert into Town_Youngsters values (0,0,1,0,0);
insert into Town_Youngsters values (1,1,0,0,1);
insert into Town_Youngsters values (0,0,1,1,0);
insert into Town_Youngsters values (1,0,1,1,0);
insert into Town_Youngsters values (0,1,1,1,1);
insert into Town_Youngsters values (1,0,1,1,1);
insert into Town_Youngsters values (1,0,1,0,1);
insert into Town_Youngsters values (0,0,1,1,1);
insert into Town_Youngsters values (1,0,1,0,0);
insert into Town_Youngsters values (0,0,1,0,0);
insert into Town_Youngsters values (1,0,1,1,1);
insert into Town_Youngsters values (0,0,1,0,0);
insert into Town_Youngsters values (1,0,1,1,0);
insert into Town_Youngsters values (1,1,1,0,1);
insert into Town_Youngsters values (1,0,1,0,0);
insert into Town_Youngsters values (0,1,1,1,1);
insert into Town_Youngsters values (0,1,0,0,1);
insert into Town_Youngsters values (1,0,0,0,0);
insert into Town_Youngsters values (1,0,0,0,0);
insert into Town_Youngsters values (1,0,1,0,0);
insert into Town_Youngsters values (0,0,1,1,1);
insert into Town_Youngsters values (1,0,1,1,0);
insert into Town_Youngsters values (1,1,1,1,1);
insert into Town_Youngsters values (1,0,1,1,1);
insert into Town_Youngsters values (1,1,1,1,0);
insert into Town_Youngsters values (0,0,1,0,0);
insert into Town_Youngsters values (1,0,1,0,0);
insert into Town_Youngsters values (1,0,0,0,0);
insert into Town_Youngsters values (1,1,1,0,1);
insert into Town_Youngsters values (0,0,1,1,1);
insert into Town_Youngsters values (1,0,1,1,0);
insert into Town_Youngsters values (0,1,1,1,1);
insert into Town_Youngsters values (0,1,1,1,0);
insert into Town_Youngsters values (0,0,1,1,1);
insert into Town_Youngsters values (1,0,1,1,0);
insert into Town_Youngsters values (1,0,1,0,1);
insert into Town_Youngsters values (1,0,1,1,0);
insert into Town_Youngsters values (1,0,1,1,1);
insert into Town_Youngsters values (0,	0,	1,	1,	0);
insert into Town_Youngsters values (0,	1,	1,	1,	1);
insert into Town_Youngsters values (1,	0,	1,	1,	1);
insert into Town_Youngsters values (0,	0,	1,	0,	0);
insert into Town_Youngsters values (0,	0,	1,	0,	1);
insert into Town_Youngsters values (1,	1,	1,	1,	1);
insert into Town_Youngsters values (1,	0,	1,	0,	1);
insert into Town_Youngsters values (0,	1,	1,	1,	0);
insert into Town_Youngsters values (1,	0,	1,	1,	1);
insert into Town_Youngsters values (1,	0,	1,	1,	0);
insert into Town_Youngsters values (0,	0,	1,	1,	1);
insert into Town_Youngsters values (0,	0,	1,	1,	1);
insert into Town_Youngsters values (0,	1,	1,	1,	0);
insert into Town_Youngsters values (1,	0,	1,	1,	0);
insert into Town_Youngsters values (0,	0,	1,	0,	0);
insert into Town_Youngsters values (1,	1,	0,	0,	0);
insert into Town_Youngsters values (1,	1,	1,	1,	1);
insert into Town_Youngsters values (0,	1,	1,	1,	1);
insert into Town_Youngsters values (0,	1,	1,	0,	0);
insert into Town_Youngsters values (0,	1,	1,	0,	1);
insert into Town_Youngsters values (1,	1,	1,	1,	0);
insert into Town_Youngsters values (1,	0,	1,	0,	1);
insert into Town_Youngsters values (0,	1,	1,	1,	1);
insert into Town_Youngsters values (0,	0,	1,	0,	0);
insert into Town_Youngsters values (1,	0,	1,	0,	1);
insert into Town_Youngsters values (1,	0,	1,	1,	1);
insert into Town_Youngsters values (1,	0,	0,	0,	0);
insert into Town_Youngsters values (0,	1,	1,	0,	1);
insert into Town_Youngsters values (0,	1,	0,	0,	0);
insert into Town_Youngsters values (0,	0,	1,	1,	1);
insert into Town_Youngsters values (1,	0,	1,	1,	1);
insert into Town_Youngsters values (0,	0,	1,	0,	0);
insert into Town_Youngsters values (1,	0,	1,	0,	0);
insert into Town_Youngsters values (1,	1,	1,	1,	0);
insert into Town_Youngsters values (0,	1,	1,	1,	1);
insert into Town_Youngsters values (0,	0,	1,	0,	0);
insert into Town_Youngsters values (1,	1,	1,	1,	1);
insert into Town_Youngsters values (1,	0,	1,	1,	1);
insert into Town_Youngsters values (0,	0,	1,	0,	0);
insert into Town_Youngsters values (1,	0,	1,	1,	1);
insert into Town_Youngsters values (0,	0,	1,	0,	0);
insert into Town_Youngsters values (0,	1,	1,	1,	1);
insert into Town_Youngsters values (0,	1,	1,	1,	1);
insert into Town_Youngsters values (0,	1,	1,	1,	1);
insert into Town_Youngsters values (1,	1,	1,	0,	1);
insert into Town_Youngsters values (0,	1,	1,	0,	1);
insert into Town_Youngsters values (1,	0,	1,	0,	1);
insert into Town_Youngsters values (1,	1,	1,	1,	1);
insert into Town_Youngsters values (1,	1,	1,	1,	1);
insert into Town_Youngsters values (0,	0,	1,	1,	1);
insert into Town_Youngsters values (0,	1,	1,	0,	1);
insert into Town_Youngsters values (1,	1,	1,	1,	1);
insert into Town_Youngsters values (0,	0,	1,	0,	0);
insert into Town_Youngsters values (1,	1,	1,	1,	1);
insert into Town_Youngsters values (0,	0,	1,	0,	0);
insert into Town_Youngsters values (0,	0,	1,	1,	1);
insert into Town_Youngsters values (0,	0,	1,	0,	0);
insert into Town_Youngsters values (1,	0,	1,	0,	0);
insert into Town_Youngsters values (1,	0,	0,	0,	0);
insert into Town_Youngsters values (0,	1,	1,	1,	1);
insert into Town_Youngsters values (0,	1,	1,	1,	0);
insert into Town_Youngsters values (1,	0,	1,	1,	0);
insert into Town_Youngsters values (1,	1,	1,	1,	1);
insert into Town_Youngsters values (1,	0,	1,	0,	1);
insert into Town_Youngsters values (0,	1,	1,	1,	0);
insert into Town_Youngsters values (0,	0,	1,	0,	1);
insert into Town_Youngsters values (0,	1,	0,	0,	1);
insert into Town_Youngsters values (0,	1,	1,	1,	1);
insert into Town_Youngsters values (1,	0,	1,	1,	0);
insert into Town_Youngsters values (1,	1,	1,	1,	1);
insert into Town_Youngsters values (0,	1,	1,	1,	1);
insert into Town_Youngsters values (0,	1,	1,	1,	1);
insert into Town_Youngsters values (0,	0,	0,	0,	0);
insert into Town_Youngsters values (0,	0,	1,	0,	1);
insert into Town_Youngsters values (0,	1,	1,	0,	0);
insert into Town_Youngsters values (1,	0,	1,	0,	0);
insert into Town_Youngsters values (1,	1,	1,	1,	1);
insert into Town_Youngsters values (0,	0,	1,	1,	1);
insert into Town_Youngsters values (0,	0,	1,	1,	0);
insert into Town_Youngsters values (0,	0,	1,	1,	0);
insert into Town_Youngsters values (0,	1,	0,	0,	1);
insert into Town_Youngsters values (1,	1,	1,	1,	0);
insert into Town_Youngsters values (1,	1,	1,	0,	1);
insert into Town_Youngsters values (1,	1,	1,	1,	1);
insert into Town_Youngsters values (0,	0,	0,	0,	1);
insert into Town_Youngsters values (1,	0,	1,	0,	1);
insert into Town_Youngsters values (0,	1,	1,	0,	1);
insert into Town_Youngsters values (1,	0,	1,	0,	0);
insert into Town_Youngsters values (0,	0,	1,	1,	0);
insert into Town_Youngsters values (1,	0,	1,	0,	0);
insert into Town_Youngsters values (1,	0,	1,	1,	1);
insert into Town_Youngsters values (0,	0,	1,	1,	0);
insert into Town_Youngsters values (0,	1,	1,	1,	0);
insert into Town_Youngsters values (1,	1,	1,	1,	1);
insert into Town_Youngsters values (1,	0,	1,	1,	0);
insert into Town_Youngsters values (0,	1,	1,	1,	0);
insert into Town_Youngsters values (0,	1,	1,	0,	1);
insert into Town_Youngsters values (1,	1,	1,	1,	1);
insert into Town_Youngsters values (0,	1,	1,	0,	1);
insert into Town_Youngsters values (1,	1,	0,	0,	1);
insert into Town_Youngsters values (1,	0,	1,	1,	1);
