--------------------------------------------------------
--  File created - Saturday-July-25-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SALES_ORDER_DETAILS
--------------------------------------------------------

  CREATE TABLE "JPANDYA"."SALES_ORDER_DETAILS" 
   (	"S_ORDER_NO" VARCHAR2(6 BYTE), 
	"PRODUCT_NO" VARCHAR2(6 BYTE), 
	"QTY_ORDER" NUMBER(8,0), 
	"QTY_DISP" NUMBER(8,0), 
	"PRODUCT_RATE" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JPANDYA.SALES_ORDER_DETAILS
SET DEFINE OFF;
Insert into JPANDYA.SALES_ORDER_DETAILS (S_ORDER_NO,PRODUCT_NO,QTY_ORDER,QTY_DISP,PRODUCT_RATE) values ('019001','P00001',4,4,525);
Insert into JPANDYA.SALES_ORDER_DETAILS (S_ORDER_NO,PRODUCT_NO,QTY_ORDER,QTY_DISP,PRODUCT_RATE) values ('019001','P07965',2,1,8400);
Insert into JPANDYA.SALES_ORDER_DETAILS (S_ORDER_NO,PRODUCT_NO,QTY_ORDER,QTY_DISP,PRODUCT_RATE) values ('019001','P07885',2,1,5250);
Insert into JPANDYA.SALES_ORDER_DETAILS (S_ORDER_NO,PRODUCT_NO,QTY_ORDER,QTY_DISP,PRODUCT_RATE) values ('019002','P00001',10,0,525);
Insert into JPANDYA.SALES_ORDER_DETAILS (S_ORDER_NO,PRODUCT_NO,QTY_ORDER,QTY_DISP,PRODUCT_RATE) values ('019003','P00001',4,4,1050);
Insert into JPANDYA.SALES_ORDER_DETAILS (S_ORDER_NO,PRODUCT_NO,QTY_ORDER,QTY_DISP,PRODUCT_RATE) values ('019003','P03453',2,2,1050);
Insert into JPANDYA.SALES_ORDER_DETAILS (S_ORDER_NO,PRODUCT_NO,QTY_ORDER,QTY_DISP,PRODUCT_RATE) values ('046866','P06734',1,1,12000);
Insert into JPANDYA.SALES_ORDER_DETAILS (S_ORDER_NO,PRODUCT_NO,QTY_ORDER,QTY_DISP,PRODUCT_RATE) values ('046866','P07965',1,0,8400);
Insert into JPANDYA.SALES_ORDER_DETAILS (S_ORDER_NO,PRODUCT_NO,QTY_ORDER,QTY_DISP,PRODUCT_RATE) values ('010008','P07975',1,0,1050);
Insert into JPANDYA.SALES_ORDER_DETAILS (S_ORDER_NO,PRODUCT_NO,QTY_ORDER,QTY_DISP,PRODUCT_RATE) values ('010008','P00001',10,5,525);
--------------------------------------------------------
--  DDL for Index SYS_C007764
--------------------------------------------------------

  CREATE UNIQUE INDEX "JPANDYA"."SYS_C007764" ON "JPANDYA"."SALES_ORDER_DETAILS" ("S_ORDER_NO", "PRODUCT_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SALES_ORDER_DETAILS
--------------------------------------------------------

  ALTER TABLE "JPANDYA"."SALES_ORDER_DETAILS" ADD PRIMARY KEY ("S_ORDER_NO", "PRODUCT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SALES_ORDER_DETAILS
--------------------------------------------------------

  ALTER TABLE "JPANDYA"."SALES_ORDER_DETAILS" ADD FOREIGN KEY ("S_ORDER_NO")
	  REFERENCES "JPANDYA"."SALES_ORDER" ("S_ORDER_NO") ENABLE;
  ALTER TABLE "JPANDYA"."SALES_ORDER_DETAILS" ADD FOREIGN KEY ("PRODUCT_NO")
	  REFERENCES "JPANDYA"."PRODUCT_MASTER" ("PRODUCT_NO") ENABLE;
