--------------------------------------------------------
--  File created - Saturday-July-25-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SALESMAN_MASTER
--------------------------------------------------------

  CREATE TABLE "JPANDYA"."SALESMAN_MASTER" 
   (	"SALESMAN_NO" VARCHAR2(6 BYTE), 
	"SAL_NAME" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(50 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"STATE" VARCHAR2(20 BYTE), 
	"PINCODE" NUMBER(6,0), 
	"SAL_AMT" NUMBER(8,2), 
	"TGT_TO_GET" NUMBER(6,2), 
	"YTD_SALES" NUMBER(6,2), 
	"REMARKS" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JPANDYA.SALESMAN_MASTER
SET DEFINE OFF;
Insert into JPANDYA.SALESMAN_MASTER (SALESMAN_NO,SAL_NAME,ADDRESS,CITY,STATE,PINCODE,SAL_AMT,TGT_TO_GET,YTD_SALES,REMARKS) values ('500001','Kiran','A/14 worli','Bombay','Maharastra',400002,3000,100,50,'Good');
Insert into JPANDYA.SALESMAN_MASTER (SALESMAN_NO,SAL_NAME,ADDRESS,CITY,STATE,PINCODE,SAL_AMT,TGT_TO_GET,YTD_SALES,REMARKS) values ('500002','Manish','65, nariman','Bombay','Maharastra',400001,3000,200,100,'Good');
Insert into JPANDYA.SALESMAN_MASTER (SALESMAN_NO,SAL_NAME,ADDRESS,CITY,STATE,PINCODE,SAL_AMT,TGT_TO_GET,YTD_SALES,REMARKS) values ('500003','Ravi','P-7 Bandra''','Bombay','Maharastra',400032,3000,200,100,'Good');
Insert into JPANDYA.SALESMAN_MASTER (SALESMAN_NO,SAL_NAME,ADDRESS,CITY,STATE,PINCODE,SAL_AMT,TGT_TO_GET,YTD_SALES,REMARKS) values ('500004','Ashish','A/5 Juhu','Bombay','Maharastra',400044,3500,200,150,'Good');
--------------------------------------------------------
--  DDL for Index SYS_C007738
--------------------------------------------------------

  CREATE UNIQUE INDEX "JPANDYA"."SYS_C007738" ON "JPANDYA"."SALESMAN_MASTER" ("SALESMAN_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SALESMAN_MASTER
--------------------------------------------------------

  ALTER TABLE "JPANDYA"."SALESMAN_MASTER" ADD PRIMARY KEY ("SALESMAN_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "JPANDYA"."SALESMAN_MASTER" ADD CHECK (ytd_sales <> 0) ENABLE;
  ALTER TABLE "JPANDYA"."SALESMAN_MASTER" ADD CHECK (tgt_to_get<>0) ENABLE;
  ALTER TABLE "JPANDYA"."SALESMAN_MASTER" ADD CHECK (sal_amt<>0) ENABLE;
  ALTER TABLE "JPANDYA"."SALESMAN_MASTER" ADD CHECK (salesman_no like '5%') ENABLE;
  ALTER TABLE "JPANDYA"."SALESMAN_MASTER" MODIFY ("YTD_SALES" NOT NULL ENABLE);
  ALTER TABLE "JPANDYA"."SALESMAN_MASTER" MODIFY ("TGT_TO_GET" NOT NULL ENABLE);
  ALTER TABLE "JPANDYA"."SALESMAN_MASTER" MODIFY ("SAL_AMT" NOT NULL ENABLE);
  ALTER TABLE "JPANDYA"."SALESMAN_MASTER" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "JPANDYA"."SALESMAN_MASTER" MODIFY ("SAL_NAME" NOT NULL ENABLE);
