services:
   namenode:
      image: apache/hadoop:3.4.1
      hostname: namenode
      user: hadoop
      container_name: namenode
      #command: ["/bin/bash", "-c", "if [ ! -d /tmp/hadoop-hadoop/dfs/name/current ]; then hdfs namenode -format; fi && hdfs namenode"]
      command: ["hdfs", "namenode"]
      ports:
        - 9870:9870
        - 9000:9000
        - 8020:8020
      env_file:
        - ./config
      environment:
          ENSURE_NAMENODE_DIR: "/tmp/hadoop-hadoop/dfs/name"
          CLUSTER_NAME: test1
          PUID: 1000 
          PGID: 100
          HADOOP_HOME: /opt/hadoop
      volumes:
        - ./shared_nn:/opt/shared_nn
        - type: volume
          source: docker-dfs-name
          target: /tmp/hadoop-hadoop/dfs/name
          volume:
            nocopy: true
         #   subpath:
      # ... other configurations
      ulimits:
        nofile:
          soft: 65536 # Adjust this value as needed
          hard: 65536 # Adjust this value as needed
   datanode:
      image: apache/hadoop:3.4.1
      container_name: datanode
      hostname: datanode
      user: hadoop
      depends_on:
        - namenode
      command: ["hdfs", "datanode"]
      ports:
        - 9864:9864
        - 9866:9866
      env_file:
        - ./config      
      environment:
         ENSURE_DATANODE_DIR: "/tmp/hadoop-hadoop/dfs/data"
         SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088" 
         PUID: 1000 
         PGID: 100
         HADOOP_HOME: /opt/hadoop
      volumes:
        - ./shared_dn:/opt/shared_dn
        - type: volume
          source: docker-dfs-data
          target: /tmp/hadoop-hadoop/dfs/data
          volume:
            nocopy: true
        #    subpath: 
      # ... other configurations
      ulimits:
        nofile:
          soft: 65536 # Adjust this value as needed
          hard: 65536 # Adjust this value as needed
   resourcemanager:
      image: apache/hadoop:3.4.1
      hostname: resourcemanager
      container_name: resourcemanager
      user: hadoop
      depends_on:
        - namenode
        - datanode
      command: ["yarn", "resourcemanager"]
      ports:
         - 8088:8088
         - 8032:8032
      env_file:
        - ./config
      volumes:
        - ./shared_rm:/opt/shared_rm
      # ... other configurations
      environment:
        HADOOP_HOME: /opt/hadoop
      ulimits:
        nofile:
          soft: 65536 # Adjust this value as needed
          hard: 65536 # Adjust this value as needed
   nodemanager:
      image: apache/hadoop:3.4.1
      container_name: nodemanager
      hostname: nodemanager
      user: hadoop
      depends_on:
        - namenode
        - datanode
        - resourcemanager
      command: ["yarn", "nodemanager"]
      ports:
         - 8042:8042
         - 8040:8040
      env_file:
        - ./config
      volumes:
        - ./shared_nm:/opt/shared_nm
      # ... other configurations
      ulimits:
        nofile:
          soft: 65536 # Adjust this value as needed
          hard: 65536 # Adjust this value as needed
   historyserver:
      image: apache/hadoop:3.4.1
      hostname: jobhistoryserver
      container_name: jobhistoryserver
      user: hadoop
      ports:
         - 8188:8188
         - 19888:19888
         - 19888:19888
         - 19890:19890
         - 10033:10033
      env_file:
        - ./config
      environment:
         SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
         HADOOP_HOME: /opt/hadoop
      # ... other configurations
      ulimits:
        nofile:
          soft: 65536 # Adjust this value as needed
          hard: 65536 # Adjust this value as needed
volumes:
  docker-dfs-name:
    name: docker-dfs-name
    external: true
  docker-dfs-data:
    name: docker-dfs-data
    external: true
