services:
   namenode:
      image: apache/hadoop:3.4.1
      hostname: namenode
      container_name: namenode
      command: ["hdfs", "namenode"]
      ports:
        - 9870:9870
        - 9000:9000
        - 8020:8020
      env_file:
        - ./config
      environment:
          ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
          CLUSTER_NAME: test1
      volumes:
        - ./shared_nn:/opt/shared_nn
      # ... other configurations
      ulimits:
        nofile:
          soft: 65536 # Adjust this value as needed
          hard: 65536 # Adjust this value as needed
   datanode:
      image: apache/hadoop:3.4.1
      container_name: datanode
      hostname: datanode
      depends_on:
        - namenode
      command: ["hdfs", "datanode"]
      ports:
        - 9864:9864
        - 9866:9866
      env_file:
        - ./config      
      environment:
         ENSURE_DATANODE_DIR: "/tmp/hadoop-root/dfs/data"
         SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088" 
      volumes:
        - ./shared_dn:/opt/shared_dn
      # ... other configurations
      ulimits:
        nofile:
          soft: 65536 # Adjust this value as needed
          hard: 65536 # Adjust this value as needed
   resourcemanager:
      image: apache/hadoop:3.4.1
      hostname: resourcemanager
      container_name: resourcemanager
      depends_on:
        - namenode
        - datanode
      command: ["yarn", "resourcemanager"]
      ports:
         - 8088:8088
         - 8032:8032
      env_file:
        - ./config
      volumes:
        - ./shared_rm:/opt/shared_rm
      # ... other configurations
      ulimits:
        nofile:
          soft: 65536 # Adjust this value as needed
          hard: 65536 # Adjust this value as needed
   nodemanager:
      image: apache/hadoop:3.4.1
      container_name: nodemanager
      hostname: nodemanager
      depends_on:
        - namenode
        - datanode
        - resourcemanager
      command: ["yarn", "nodemanager"]
      ports:
         - 8042:8042
         - 8040:8040
      env_file:
        - ./config
      volumes:
        - ./shared_nm:/opt/shared_nm
      # ... other configurations
      ulimits:
        nofile:
          soft: 65536 # Adjust this value as needed
          hard: 65536 # Adjust this value as needed
   historyserver:
      image: apache/hadoop:3.4.1
      hostname: jobhistoryserver
      container_name: jobhistoryserver
      ports:
         - 8188:8188
         - 19888:19888
         - 19888:19888
         - 19890:19890
         - 10033:10033
      env_file:
        - ./config
      environment:
         SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
      # ... other configurations
      ulimits:
        nofile:
          soft: 65536 # Adjust this value as needed
          hard: 65536 # Adjust this value as needed
