--------------------------------------------------------
--  File created - Wednesday-July-22-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADEPARTMENT
--------------------------------------------------------

  CREATE TABLE "JPANDYA"."ADEPARTMENT" 
   (	"DEPT_ID" NUMBER(6,0), 
	"DEPT_NAME" VARCHAR2(20 BYTE), 
	"TOTAL_EMPLOYEES" NUMBER(5,0), 
	"FACULTY_ID" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JPANDYA.ADEPARTMENT
SET DEFINE OFF;
Insert into JPANDYA.ADEPARTMENT (DEPT_ID,DEPT_NAME,TOTAL_EMPLOYEES,FACULTY_ID) values (1,'Computer
',100,1);
Insert into JPANDYA.ADEPARTMENT (DEPT_ID,DEPT_NAME,TOTAL_EMPLOYEES,FACULTY_ID) values (2,'Electronics',80,1);
Insert into JPANDYA.ADEPARTMENT (DEPT_ID,DEPT_NAME,TOTAL_EMPLOYEES,FACULTY_ID) values (3,'IT',75,1);
Insert into JPANDYA.ADEPARTMENT (DEPT_ID,DEPT_NAME,TOTAL_EMPLOYEES,FACULTY_ID) values (4,'Civil',25,1);
Insert into JPANDYA.ADEPARTMENT (DEPT_ID,DEPT_NAME,TOTAL_EMPLOYEES,FACULTY_ID) values (5,'IC',70,1);
Insert into JPANDYA.ADEPARTMENT (DEPT_ID,DEPT_NAME,TOTAL_EMPLOYEES,FACULTY_ID) values (null,'dummy',1000,null);
